### ISSUE TITLE
The role of scaling_factor for autoencoder inputs (CONFIG_49)

### ISSUE THREAD

**Issue by au540368** [weiHelloWorld/accelerated_sampling_with_autoencoder#59]
Hello Wei,

First of all thank you for making your code available.
I am currently trying to make PC projection plots for Alanine dipeptide and Trp_cage, and noticed that cartesian coordinate inputs are consistently divided by a scaling factor (5 for Alanine dipeptide and 20 for Trp_cage) before its passed to the autoencoder.

What is the reasoning behind a scaled down input and how to infer the specific scale value for a system? My hope is to test the framework on another peptide. 

Best regards
Kasper

**Comment by weiHelloWorld** [comment]
Hi Kasper,

The scaling factors are used for training purposes, to make sure all input and output data should be in a reasonable range (e.g. [-1, 1] or [0, 1]).  I found that proper scaling would improve training results in practice.

In the code I used fixed scaling factors just for convenience of analysis.  There are also alternative ways to do this, for instance, scale all features by maximum absolute magnitude of features in the dataset, or do featurewise scaling (e.g. with http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html).  

Hope it helps!

Wei
