### ISSUE TITLE
Parameters for WHAM unbiasing

### ISSUE THREAD

**Issue by au540368** [weiHelloWorld/accelerated_sampling_with_autoencoder#60]
Hi again Wei!
Thank you for the quick reply on the scaling factor - it was very helpful!

I am currently trying to reproduce your results for Alanine dipeptide before moving on to testing another protein, but i'm running into trouble with the WHAM unbiasing procedure. It is my understanding that you are using the scripts provided on: https://bitbucket.org/andrewlferguson/bayeswham_python.

My questions:
Are you using a modified version of these scripts?
What are the parameters used?

What i am doing: I ran 10 MESA iterations on alanine dipeptide and used the "generate_mat_file_for_WHAM_reweighting()" function from autoencoder.py on the entire 10 iterations of biased data, and see that the formats are exactly what is required from the examples of running the BayesWHAM.py script, so far so good. Though when i feed this data to BayesWHAM in a naive way (using the parameters from the examples found in the link), I quickly get errors relating to division overflow (line 474 BayesWHAM.py)

Best regards
Kasper

**Comment by weiHelloWorld** [comment]
Hi Kasper,

I made a few modifications on the original package and had a fork here: https://bitbucket.org/kengyangyao/bayeswham_python, but I did not actually change the computation part of the code.  You may find my parameters in this file: https://bitbucket.org/kengyangyao/bayeswham_python/src/master/build.sh, let me know if you have any questions.

Thank you!

**Comment by au540368** [comment]
Hi Wei,
Using your parameters and script i get the same errors in BayesWHAM.py:
'''
...
	Processing of simulation 283 of 287 complete
	Processing of simulation 284 of 287 complete
	Processing of simulation 285 of 287 complete
	Processing of simulation 286 of 287 complete
	Processing of simulation 287 of 287 complete
DONE!

Computing MAP estimate of probability distribution by direct iteration of the WHAM equations...
BayesWHAM.py:474: RuntimeWarning: overflow encountered in divide
  f_i = np.divide( 1, np.dot(c_il_NZ,p_l_NZ) )
	Iteration 1, max(dp) =     4.58804e-01
'''
I suspect that maybe i have made some mistake generating the mat files. I used small script for this:
'''
from ANN_simulation import *
dest_out_networks ="../resources/backup_data/Alanine_dipeptide_normalsorting/"
dest_coor_files ="../target/backup_data/Alanine_dipeptide_normalsorting/" #will take all coordinate files 
dest_mat_files ="../resources/backup_data/Alanine_dipeptide_normalsorting/BayesWHAM/"
iteration_to_analyse = 10 
_scaling_factor=CONFIG_49
generate_coor_files = True
_mode="Bayes"  
_input_data_type='Cartesian'  # 'cossin' or 'Cartesian'
_num_of_bins = 20

if generate_coor_files:
        molecule_type.generate_coordinates_from_pdb_files(path_for_pdb=dest_coor_files)

network = autoencoder.load_from_pkl_file(dest_out_networks+"network_{}.pkl".format(iteration_to_analyse)) 

network.generate_mat_file_for_WHAM_reweighting(dest_coor_files, folder_to_store_files=dest_mat_files, mode=_mode, input_data_type=_input_data_type, scaling_factor=_scaling_factor, num_of_bins=_num_of_bins)   
'''

Though i have not used the function get_proper_potential_centers_for_WHAM() from autoencoder.py, is this necessary? Also, could it be a problem related to the number of bins i chose?

Thank you so much for your help.
Cheers
Kasper

**Comment by weiHelloWorld** [comment]
Hi Kasper,

I see.  Can you do a scatter plot of the CVs collected in WHAM runs?  I wonder if there exists some poorly sampled region in CV space which affects computation.  

`get_proper_potential_centers_for_WHAM()` is not necessary, as long as your WHAM runs generate CVs that well sample explored region that should be fine.

`num_of_bins=20` should be fine based on my experience, but you may also try 10 to see if that solves the issue.

Let me know if you have any updates.

**Comment by au540368** [comment]
Hi Wei,

I'll try on another run of simulations, i have done (though with reverse sorting mode) - ill get back on that.

Here are the plots of the current MESA run which generates the WHAM error:
![phi_on_pc_iter10](https://user-images.githubusercontent.com/37177062/48488156-653e9d80-e820-11e8-8659-bdceba8dd1ab.png)
![psi_on_pc_iter10](https://user-images.githubusercontent.com/37177062/48488164-68398e00-e820-11e8-882a-48e295a450e0.png)
![phipsi_iter10](https://user-images.githubusercontent.com/37177062/48488170-6a035180-e820-11e8-9654-1809015d1613.png)

Best regards
Kasper

**Comment by weiHelloWorld** [comment]
Hi Kasper,

Thanks for the update!  Can you also show me the scatter plot of CVs
generated by all biased simulations in WHAM?



Best Regards
----------------------
Wei Chen

IME, UChicago

Physics, UIUC

**Comment by au540368** [comment]
Hi Wei,

I managed to run BayesWHAM on the other simulation batch without errors ( :) ! ), and from the plots the simulations were converged much better. I think you're right about convergence, though i didnt suspect convergence to influence the ability to run WHAM. 

I am not sure what you mean by CVs
generated by all biased simulations _in WHAM_? I have CV plots _per iteration_ with the biased data projected through the current autoencoder like the above. The above is for the last iteration #10 btw :).

Cheers 
Kasper

**Comment by weiHelloWorld** [comment]
Hi Kasper,

Glad to know it works for you!

By " CVs generated by all biased simulations in WHAM" I mean you may
project data you collected in WHAM (i.e. a bunch of biased simulations
using the same autoencoder) to CV space defined by that  autoencoder.  Say
if you use model `ae_1` to run biased simulations in WHAM, and data you
collected in these biased simulations (not in exploration iterations) are
`X` (mean-free Cartesian coordinates in your case), and you may scatter
plot `ae_1.get_PCs(X)` to see if these biased simulations well cover the
region of interest in CV space.




Best Regards
----------------------
Wei Chen

IME, UChicago

Physics, UIUC

**Comment by au540368** [comment]
Alright! Thank you so much for your time.

**Comment by weiHelloWorld** [comment]
You are welcome!  I am going to close this issue.
