### ISSUE TITLE
Link broken?

### ISSUE THREAD

**Issue by ramansbach** [weiHelloWorld/accelerated_sampling_with_autoencoder#62]
It looks like this link in the dependencies no longer functions (did the code get moved somewhere maybe?):

PLUMED (ANN included): https://github.com/weiHelloWorld/plumed2

**Comment by weiHelloWorld** [comment]
Sorry I have moved it to another repository without updating README: https://github.com/weiHelloWorld/plumed_additional.  If you would like to use plumed version of ANN force, you need to checkout https://github.com/plumed/plumed2 and then copy `ANN.cpp` to `plumed2/src/function`.   Originally I implemented it as a CV, but I found it would be better to implement it as a general function.  Let me know if you have any questions.
