### ISSUE TITLE
[question] Could it be possible to use this package to help determine CV for simulation of voltage gating of gap junction channels ?

### ISSUE THREAD

**Issue by KestutisMa** [weiHelloWorld/accelerated_sampling_with_autoencoder#63]
Hi Wei,
Could this package be used to help determine CV for simulation of voltage gating of gap junction channels?

Best regards
Kestutis Maciunas
PhD
Lithuanian University of Health Sciences

**Comment by weiHelloWorld** [comment]
Hi Kestutis,

Thanks for your interest!

I am not quite familiar with simulation of voltage gating of gap junction channels, but if you are trying to find low-dimensional CVs from high-dimensional features, autoencoder could be helpful.

Best Regards,

Wei
